### ISSUE TITLE
The x is half hidden

### ISSUE THREAD

**Issue by Torsten-K** [luckyshot/cookie-law-simple-script#1]
Very nice and slim script. The only issue is, that the x is half hidden by the scrollbar. It should have a slightly larger distance to the right edge of the browser window.

![x-half-hidden](https://user-images.githubusercontent.com/806012/84441904-e8161d00-ac3c-11ea-815f-c97c6d788852.jpg)

```
#cookie-law-div button {
    …
    padding-right: 32px;
}
```

**Comment by luckyshot** [comment]
Thanks @Torsten-K for reporting, it's been fixed 👍
